### ISSUE TITLE
long sync fails in regtest

### ISSUE THREAD

**Issue by josedahlquist** [rsksmart/rskj#1308]
### Summary

Trying a local private network using regtest fails to sync nodes.

```
2020-09-09-20:00:37.0969 DEBUG [syncprocessor]  Receiving syncState from node NodeID{7b7aab8fb705ecd19346c4e0346068c406db57b6379c836e80752cf33bdb1aaf8878635e8321e3739856115c58be707ce639d69a43f11bb05108a5b097d8e618} block 0 bb1fc1ec0f5a6a0afebc8c031fde848e6b5338edbc563341d878f894e670e3c8
2020-09-09-20:00:43.0078 ERROR [messagehandler]  Unexpected error processing: MessageTask{sender=7b7aab8fb705ecd19346c4e0346068c406db57b6379c836e80752cf33bdb1aaf8878635e8321e3739856115c58be707ce639d69a43f11bb05108a5b097d8e618 | localhost/127.0.0.1:50687, message=Message{type=SKELETON_REQUEST_MESSAGE}}
java.lang.IllegalArgumentException: A block header must have 16/17 elements or 19/20 including merged-mining fields but it had 19
	at org.ethereum.core.BlockFactory.decodeHeader(BlockFactory.java:140)
	at org.ethereum.core.BlockFactory.decodeBlock(BlockFactory.java:69)
	at org.ethereum.core.BlockFactory.decodeBlock(BlockFactory.java:59)
	at org.ethereum.db.IndexedBlockStore.getBlock(IndexedBlockStore.java:282)
	at org.ethereum.db.IndexedBlockStore.getBlockByHash(IndexedBlockStore.java:260)
	at org.ethereum.db.IndexedBlockStore.getChainBlockByNumber(IndexedBlockStore.java:250)
	at co.rsk.core.bc.BlockChainImpl.getBlockByNumber(BlockChainImpl.java:417)
	at co.rsk.net.NodeBlockProcessor.getBlockFromBlockchainStore(NodeBlockProcessor.java:340)
	at co.rsk.net.NodeBlockProcessor.processSkeletonRequest(NodeBlockProcessor.java:267)
	at co.rsk.net.messages.MessageVisitor.apply(MessageVisitor.java:146)
	at co.rsk.net.messages.SkeletonRequestMessage.accept(SkeletonRequestMessage.java:61)
	at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:103)
	at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:190)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

1. Start a full node resetting its database and with the miner client enabled.
2. Let this node sync advance the blockchain for a while (make sure it is enough for the database to be dumped into the db dir)
3. Stop this node.
4. Start it again with the miner client disabled (the miner client is not relevant in reality).
5. Start a second full node resetting its database, connected to this one, and with the miner client disabled.
6. The second node will try to sync with the first one.
7. You will see the mentioned exception in the first node logs.

### Local mitigation

I've been able to bypass this issue by changing the Papyrus network upgrade activation height to `1`. By doing this the issue is removed and the nodes are sync without any issue.

This points up that the issue is likely related to the block header structure of the genesis block been affected by UMM activation in height 0.

**Comment by aeidelman** [comment]
I'm closing this issue in favor of #1525
