### ISSUE TITLE
The class TrieConverter is not thread-safe

### ISSUE THREAD

**Issue by SergioDemianLerner** [rsksmart/rskj#1540]
When processing two blocks simultaneously from two different threads I got this exception: 

```
Exception in thread "Thread-1" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at co.rsk.trie.TrieConverter.getOrchidAccountTrieRoot(TrieConverter.java:54)
	at co.rsk.db.StateRootHandler.convert(StateRootHandler.java:67)
	at co.rsk.core.bc.BlockExecutor.validateStateRoot(BlockExecutor.java:213)
	at co.rsk.core.bc.BlockExecutor.validate(BlockExecutor.java:151)
	at co.rsk.core.bc.BlockExecutor.executeAndValidate(BlockExecutor.java:133)
	at co.rsk.cli.tools.ExecuteBlocks.executeSingleThread(ExecuteBlocks.java:253)
	at co.rsk.cli.tools.ExecuteBlocks.lambda$execute$0(ExecuteBlocks.java:305)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This shows that the class TrieConverter is not thread-safe. Maybe it should be?

**Comment by SergioDemianLerner** [comment]
getOrchidAccountTrieRoot could be made synchronized
