### ISSUE TITLE
config error Unexpected config value SimpleConfigObject({"enabled":true}) for key path `prune`. See expected.conf for the expected settings

### ISSUE THREAD

**Issue by liangcansun** [rsksmart/rskj#1555]
2021-06-10-09:56:28.311 ERROR [config]  Unexpected config value SimpleConfigObject({"enabled":true}) for key path `prune`. See expected.conf for the expected settings

my rsk.conf :
blockchain.config.name = "main"

database.dir = /root/.rsk/database/mainnet

rpc {
providers : {
    web: {
        cors: "localhost",
        http: {
            enabled: true,
            bind_address = "0.0.0.0",
            hosts = ["localhost"]
            port: 4444,
            }
        ws: {
            enabled: false,
            bind_address: "0.0.0.0",
            port: 4445,
            }
        }
    }

    modules = [
        {
            name: "eth",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "net",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "rpc",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "web3",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "evm",
            version: "1.0",
            enabled: "false"
        },
        {
            name: "sco",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "txpool",
            version: "1.0",
            enabled: "true",
        },
        {
            name: "debug",
            version: "1.0",
            enabled: "true",
        },        
        {
            name: "personal",
            version: "1.0",
            enabled: "true"
        }
    ]
}

**Comment by liangcansun** [comment]
in my rsk.conf no 'prune'. but in node.conf have 'prune'. 

the node log :

2021-06-10-11:19:41.422 INFO [config]  Config ( yes ): user properties from -Drsk.conf.file file '/root/.rsk/rsk.conf'
2021-06-10-11:19:41.428 INFO [config]  Config ( yes ): default properties from installer '/etc/rsk/node.conf'
2021-06-10-11:19:41.465 ERROR [config]  Unexpected config value SimpleConfigObject({"enabled":true}) for key path `prune`. See expected.conf for the expected settings

**Comment by fedejinich** [comment]
It's this the stacktrace?

```
2021-06-09-09:37:35.083 WARN [c.g.j.JsonRpcBasicServer] Error in JSON-RPC Service
java.lang.NullPointerException: null
at co.rsk.mine.MinerServerImpl.getWork(MinerServerImpl.java:355)
at co.rsk.rpc.modules.mnr.MnrModuleImpl.getWork(MnrModuleImpl.java:55)
at co.rsk.rpc.Web3MnrModule.mnr_getWork(Web3MnrModule.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:516)
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:357)
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:288)
at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:256)
at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:63)
at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:41)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:31)
at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:25)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:96)
at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:21)
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:66)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
2021-06-09-09:37:35.084 ERROR [web3] JsonRPC error when for method public default co.rsk.mine.MinerWork co.rsk.rpc.Web3MnrModule.mnr_getWork() with arguments []
java.lang.NullPointerException: null
```

**Comment by fedejinich** [comment]
https://github.com/rsksmart/rskj/issues/1551

**Comment by liangcansun** [comment]
no,That's another question。The problem now is the configuration file of rsk.conf。

**Comment by nagarev** [comment]
Hi @liangcansun! If I'm not understanding wrong, you said that in the `expected.conf` file there is a setting to enable or disable `prune` but you are not including it in your `rsk.conf` file. Is that Okay? The thing is that I'm not seeing that setting in the `expected.conf` file. Can you send a screenshot of what you're seeing? Thanks in advance!

**Comment by nagarev** [comment]
Hi @liangcansun, the prune feature was removed some time ago, so we've updated [the documentation](https://developers.rsk.co/rsk/node/configure/reference/) to reflect that. I will close this issue, thanks for the report!
