### ISSUE TITLE
Testnet node stuck after upgrade to 6.0.0

### ISSUE THREAD

**Issue by jajaislanina** [rsksmart/rskj#2273]
Node was running v5.3.0, missed the HF on block 4,927,100 and quickly upgraded to 6.0.0.
After starting the node it worked for some blocks and then got stuck on block 4,927,121 with logs:

```
14:08:12.785 [message handler] ERROR panic - bridgeexecute: Error executing: REGISTER_BTC_COINBASE_TRANSACTION
14:08:12.785 [message handler] ERROR panic - Stack Trace:java.lang.Throwable: null	
at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)	
at co.rsk.peg.Bridge.execute(Bridge.java:394)	
at org.ethereum.vm.program.Program.executePrecompiledAndHandleError(Program.java:1473)	
at org.ethereum.vm.program.Program.callToPrecompiledAddress(Program.java:1439)	
at org.ethereum.vm.VM.doCALL(VM.java:1518)	
at org.ethereum.vm.VM.executeOpcode(VM.java:2002)	
at org.ethereum.vm.VM.steps(VM.java:2094)	
at org.ethereum.vm.VM.play(VM.java:2128)	
at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:434)	
at org.ethereum.core.TransactionExecutor.executeTransaction(TransactionExecutor.java:140)	
at co.rsk.core.bc.BlockExecutor.executeInternal(BlockExecutor.java:295)	
at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:226)	
at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:252)	
at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:158)	
at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:207)	
at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:184)	
at co.rsk.net.AsyncNodeBlockProcessor.processBlock(AsyncNodeBlockProcessor.java:124)	
at co.rsk.net.messages.MessageVisitor.apply(MessageVisitor.java:105)	
\at co.rsk.net.messages.BlockMessage.accept(BlockMessage.java:52)	
at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:155)	
at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:317)	
at java.base/java.lang.Thread.run(Unknown Source)
14:08:12.789 [message handler] ERROR blockexecutor - Block 4927122 [8fa265a2b1705e29d0fd1047f656d69b131e312a27361b3613c580b175677c0c] given State Root is invalid
```
Tried to rewind:
`java -cp rsk.jar co.rsk.cli.tools.RewindBlocks -rbc`
```
2024-03-20-14:16:32.0590 INFO [clitool] [main]  RewindBlocks started
2024-03-20-14:16:32.0918 INFO [clitool] [main]  No inconsistent block has been found. Nothing to do
2024-03-20-14:16:32.0918 INFO [clitool] [main]  RewindBlocks finished
```
Tried to go to a fixed block before the HF:

`java -cp rsk.jar co.rsk.cli.tools.RewindBlocks -b=4927050`

```
2024-03-20-14:13:40.0581 INFO [clitool] [main]  RewindBlocks started
2024-03-20-14:13:40.0863 INFO [clitool] [main]  Highest block number stored in db: -1
2024-03-20-14:13:40.0864 INFO [clitool] [main]  Block number to rewind to: 4927050
2024-03-20-14:13:40.0864 INFO [clitool] [main]  No need to rewind
2024-03-20-14:13:40.0864 INFO [clitool] [main]  RewindBlocks finished
```

No changes.
Anything i can do aside from syncing from scratch?

**Comment by nebojsa-ristovic** [comment]
DB got corrupted because we didn't upgrade our node on time - we missed ARROWHEAD hardfork.
