### ISSUE TITLE
Invalid block identifier '{' with eth_call method in json rpc server

### ISSUE THREAD

**Issue by capitalist42** [rsksmart/rskj#2289]
I called the rsk node's json rpc endpoint with the payload.
```
{
  "jsonrpc": "2.0",
  "method": "eth_call",
  "params": [
    {
       "data": "0x06fdde03",
       "gas": "0x2faf080",
       "to": "0xdb107fa69e33f05180a4c2ce9c2e7cb481645c2d"
    },
    {
      "blockHash": "0x7b443d9e0c0748ecf9d33d8d64097ce6e2dce676d3b8767295cb377f9695d91d"
    }
   ],
  "id": 7035
}

```
But it returned
```
{
    "jsonrpc": "2.0",
    "id": 7035,
    "error": {
        "code": -32602,
        "message": "Invalid block identifier '{'"
    }
}
```

the application version
```
ARROWHEAD-6.1.0
```
 
the application log
```
2024-04-16-09:59:23.0431 WARN [c.g.j.JsonRpcBasicServer] [nioEventLoopGroup-3-1] [rpcReqID=mX5IveEMbNjJ0cF]  Error in JSON-RPC Service
org.ethereum.rpc.exception.RskJsonRpcRequestException: Invalid block identifier '{'
	at org.ethereum.rpc.exception.RskJsonRpcRequestException.invalidParamError(RskJsonRpcRequestException.java:42)
	at org.ethereum.rpc.parameters.BlockIdentifierParam.<init>(BlockIdentifierParam.java:45)
	at org.ethereum.rpc.parameters.BlockIdentifierParam$Deserializer.deserialize(BlockIdentifierParam.java:65)
	at org.ethereum.rpc.parameters.BlockIdentifierParam$Deserializer.deserialize(BlockIdentifierParam.java:55)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2025)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1175)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.convertJsonToParameters(JsonRpcBasicServer.java:637)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.invoke(JsonRpcBasicServer.java:582)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleObject(JsonRpcBasicServer.java:455)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleJsonNodeRequest(JsonRpcBasicServer.java:290)
	at co.rsk.rpc.netty.JsonRpcCustomServer.handleJsonNodeRequest(JsonRpcCustomServer.java:58)
	at com.googlecode.jsonrpc4j.JsonRpcBasicServer.handleRequest(JsonRpcBasicServer.java:249)
	at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:77)
	at co.rsk.rpc.netty.JsonRpcWeb3ServerHandler.channelRead0(JsonRpcWeb3ServerHandler.java:47)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:31)
	at co.rsk.rpc.netty.Web3HttpMethodFilterHandler.channelRead0(Web3HttpMethodFilterHandler.java:25)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.serveRequest(JsonRpcWeb3FilterHandler.java:125)
	at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:95)
	at co.rsk.rpc.netty.JsonRpcWeb3FilterHandler.channelRead0(JsonRpcWeb3FilterHandler.java:22)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at co.rsk.rpc.netty.LogTracingFilterHandler.channelRead0(LogTracingFilterHandler.java:32)
	at co.rsk.rpc.netty.LogTracingFilterHandler.channelRead0(LogTracingFilterHandler.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by capitalist42** [comment]
@Vovchyk 
I am using docker image "rsksmart/rskj:ARROWHEAD-6.1.0" but
the result of calling "web3_clientVersion"
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "RskJ/6.0.0/Linux/Java1.8/ARROWHEAD-"
}
```

**Comment by capitalist42** [comment]
@Vovchyk problem resolved.
the rsk.jar inside the "/var/lib/rsk" directory did not get updated when I changed the docker image version.
It was due to the fact that I mounted volume to "/var/lib/rsk" directory.
