### ISSUE TITLE
web3.personal.newAccount()

### ISSUE THREAD

**Issue by xiaofeizhu69** [rsksmart/rskj#467]
Hello 
  When i test RSK, i want to create new account ,but when i call the function "web3.personal.newAccount()"  it is always error:

RSK > web3.personal.newAccount()
Error during execution of script.

Error: The local wallet feature is disabled
    at Object.InvalidResponse (/data/rskconsole/console/node_modules/web3/lib/web3/errors.js:35:16)
    at RequestManager.send (/data/rskconsole/console/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Personal.send [as newAccount] (/data/rskconsole/console/node_modules/web3/lib/web3/method.js:145:58)
    at eval (eval at <anonymous> (/data/rskconsole/console/console.js:51:18), <anonymous>:1:15)
    at Interface.<anonymous> (/data/rskconsole/console/console.js:51:18)
    at Interface.emit (events.js:159:13)
    at Interface._onLine (readline.js:287:10)
    at Interface._line (readline.js:642:8)
    at Interface._ttyWrite (readline.js:922:14)
    at ReadStream.onkeypress (readline.js:165:10)

**Comment by bcodesido** [comment]
Hi,
It seems you need to  enable your wallet you must set `enabled = true` in that section. An example of how it looks when is propertly configured:
```
walllet {
    enabled = true
    accounts = [ ]
}
```

For any other future technical question, please refer to our [gitter channel](https://gitter.im/rsksmart/rskj)
