### ISSUE TITLE
Java compile local RSK

### ISSUE THREAD

**Issue by hstemplewski** [rsksmart/rskj#468]
I try to launch RskJ using intelliJ, after set up configuration, and click run button i got this error: 

```
objc[63210]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java (0x10fab44c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10fb404e0). One of the two will be used. Which one is undefined.
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'staticMessages' defined in file [/Users/hstemplewski/Documents/ReactPoland/experty/rsk/rskj/rskj-core/out/production/classes/org/ethereum/net/message/StaticMessages.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.ethereum.config.SystemProperties]: Error creating bean with name 'rskSystemProperties' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.config.RskSystemProperties]: Factory method 'rskSystemProperties' threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo(); nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rskSystemProperties' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.config.RskSystemProperties]: Factory method 'rskSystemProperties' threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo()
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:843)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at co.rsk.Start.main(Start.java:83)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rskSystemProperties' defined in org.ethereum.config.DefaultConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.config.RskSystemProperties]: Factory method 'rskSystemProperties' threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo()
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:814)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	... 14 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [co.rsk.config.RskSystemProperties]: Factory method 'rskSystemProperties' threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 27 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo()
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:136)
	at co.rsk.config.RskSystemProperties.<init>(RskSystemProperties.java:51)
	at org.ethereum.config.DefaultConfig.rskSystemProperties(DefaultConfig.java:136)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$d38bcadb.CGLIB$rskSystemProperties$0(<generated>)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$d38bcadb$$FastClassBySpringCGLIB$$8f8f962a.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$d38bcadb.rskSystemProperties(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 28 more
Caused by: java.lang.RuntimeException: Error validating config method: public java.lang.String org.ethereum.config.SystemProperties.genesisInfo()
	at org.ethereum.config.SystemProperties.validateConfig(SystemProperties.java:227)
	at org.ethereum.config.SystemProperties.<init>(SystemProperties.java:125)
	... 40 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.ethereum.config.SystemProperties.validateConfig(SystemProperties.java:224)
	... 41 more
Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'genesis'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
	at org.ethereum.config.SystemProperties.genesisInfo(SystemProperties.java:660)
	... 46 more
```

**Comment by hstemplewski** [comment]
I try to update java to newest version `1.8.0_162` but it not help

**Comment by ajlopez** [comment]
Which branch are you using? If it is master, we changed some config file properties recently

**Comment by hstemplewski** [comment]
sure master, i try to compile it today.

**Comment by ajlopez** [comment]
If you have some of these properties in your config file, rename them:

peer.discovery.bind.ip -> bind.address
peer.listen.port -> peer.port
peer.external.ip -> public.ip
rpc.host -> rpc.address

We could use the gitter channel for these technical questions https://gitter.im/rsksmart/rskj

**Comment by hstemplewski** [comment]
all of this is renamed yet. And still not works.

**Comment by aeidelman** [comment]
Closing due to lack of response.
