### ISSUE TITLE
Can't connect to Regnet running on Docker

### ISSUE THREAD

**Issue by varshard** [rsksmart/rskj#632]
I'm trying to use truffle with Rootstock's Regnet running on Docker, but can't connect with it via port 4444. 

I run Regnet by running using command 
`docker run -d --name regtest-node-01  -p 4444:4444 -p 30305:30305 regtest`

When I run `truffle console --network rskRegnet`
I got this message
```
Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```

Here is my truffle configuration.
```
rskRegnet: {
      host: "localhost",
      port: 4444,
      network_id: "*" // Match any network id
    },
```

*Log*
I go into Regnet container and execute `cat /var/log/rsk/rsk.log` to get log and got this.

```
2018-08-20-15:16:26.136 INFO [config]  Config ( yes ): user properties from -Drsk.conf.file file '/etc/rsk/node.conf'
2018-08-20-15:16:26.180 INFO [config]  Config ( yes ): default properties from installer '/etc/rsk/node.conf'
2018-08-20-15:16:27.155 INFO [general]  Public IP wasn't set or resolved, using checkip.amazonaws.com to identify it...
2018-08-20-15:16:27.779 ERROR [general]  Can't get public IP
java.lang.IllegalArgumentException: Invalid address: '171.99.160.48, 171.99.160.48'
	at org.ethereum.config.SystemProperties.tryParseIpOrThrow(SystemProperties.java:736)
	at org.ethereum.config.SystemProperties.getMyPublicIpFromRemoteService(SystemProperties.java:557)
	at org.ethereum.config.SystemProperties.getPublicIp(SystemProperties.java:540)
	at org.ethereum.config.DefaultConfig.peerExplorer(DefaultConfig.java:210)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$94f37abf.CGLIB$peerExplorer$9(<generated>)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$94f37abf$$FastClassBySpringCGLIB$$9d77e34b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.ethereum.config.DefaultConfig$$EnhancerBySpringCGLIB$$94f37abf.peerExplorer(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1021)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:814)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1148)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:843)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at co.rsk.SpringNodeBootstrapper.<init>(SpringNodeBootstrapper.java:43)
	at co.rsk.Start.main(Start.java:31)
Caused by: java.net.UnknownHostException: 171.99.160.48, 171.99.160.48: Name or service not known
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at org.ethereum.config.SystemProperties.tryParseIpOrThrow(SystemProperties.java:734)
	... 41 common frames omitted
```

**Comment by tinchou** [comment]
I think you have an issue with your configuration file. Check the line `Invalid address: '171.99.160.48, 171.99.160.48'`.
