### ISSUE TITLE
Block synchonization issue in Testnet/Orchid 0.5.0

### ISSUE THREAD

**Issue by dabrosimov** [rsksmart/rskj#654]
A while ago clients started to complain that the blocks are not added anymore.

Now when checking the block number I see that the last one is:

`{"jsonrpc":"2.0","id":779,"result":"0xd06fe"}`

Which is **853758** and the hash of the block is 0xe15c752defb41286c7637fa3bb5b79b9a0b0998720a358e7cb4fb738a014cbcf. However if I check the same number here - https://explorer.testnet.rsk.co/block/853758, I see that the block hash is: 0xb8c7f063648a09893352fe147885be1d1a1410c58f3d2d04dd822e8e6477b80b

Manually I have found that there is a difference in blocks starting from block number **851825**.

If I try to get info about that block from here https://explorer.testnet.rsk.co/block/851825, I see that the hash is 0xdc4c956a05a21f1dc21a6d5cc71a59d417f5c35e8c2c3604453b3e52b51d376e.

If I try to get the same block from my node:

`{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xCFF71", true],"id":779}`

It returns a different hash: 0x06390bc536de1e4357553832396df29867e1afd93a6b8bbc1f8efdace13f4348

The previous block (851824) is the same as here https://explorer.testnet.rsk.co/block/851824.

So something happened after adding the 851824 block.

There is nothing suspicious in logs except the only one error:

```
2018-10-02-08:11:14.774 TRACE [syncprocessor]  Send body request block 854954 hash 6f7ed8 to peer NodeID{472b333f53abd4e2fd1a1b90c7ea9a42b9f61b2642006481eb40df37e42565143850f12b018d08f260e047d6b102ffe753a2e77ab5c40c1f044dda0260ad6515}
2018-10-02-08:11:14.774 DEBUG [messageProcess]  Message[BODY_RESPONSE_MESSAGE] processed after [56845960] nano.
2018-10-02-08:11:14.774 DEBUG [messageProcess]  Queued Messages: 0
2018-10-02-08:11:14.774 TRACE [syncprocessor]  Process body response from node NodeID{5a94d1bcc70d8ecf1b84ca9409ab773ab8ed6e084d69db1a9d86ddc4f35ec4185dd6715f868f999c120fbe5f428e261237947cf75a34bd9f86b4ec1970e8b0ab}
2018-10-02-08:11:14.775 TRACE [blocksyncservice]  Trying to add to blockchain
2018-10-02-08:11:14.775 TRACE [blocksyncservice]  Trying to add block 851455 552998
2018-10-02-08:11:14.784 ERROR [newtrie]  Error non existent trie with hash 8684ff6cad9b515af78905c32f0c59663c2976953315cdfce26703692ff33d18
2018-10-02-08:11:14.784 ERROR [panic]  newtrie: Error creating trie from message 8684ff6cad9b515af78905c32f0c59663c2976953315cdfce26703692ff33d18
2018-10-02-08:11:14.784 ERROR [panic]  Stack Trace:
java.lang.Throwable: null
	at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)
	at co.rsk.trie.TrieImpl.getSnapshotTo(TrieImpl.java:1148)
	at co.rsk.db.ContractDetailsImpl.getSnapshotTo(ContractDetailsImpl.java:370)
	at co.rsk.db.RepositoryImpl.getContractDetails(RepositoryImpl.java:153)
	at co.rsk.db.RepositoryImpl.loadAccount(RepositoryImpl.java:386)
	at org.ethereum.db.RepositoryTrack.loadAccount(RepositoryTrack.java:138)
	at org.ethereum.db.RepositoryTrack.getAccountState(RepositoryTrack.java:93)
	at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:270)
	at org.ethereum.vm.program.Program.getCodeAt(Program.java:1032)
	at org.ethereum.vm.program.Program.getCodeAt(Program.java:1028)
	at org.ethereum.vm.VM.doCODESIZE(VM.java:780)
	at org.ethereum.vm.VM.executeOpcode(VM.java:1729)
	at org.ethereum.vm.VM.steps(VM.java:1952)
	at org.ethereum.vm.VM.play(VM.java:1983)
	at org.ethereum.core.TransactionExecutor.go(TransactionExecutor.java:357)
	at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:229)
	at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:186)
	at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:270)
	at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:183)
	at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:191)
	at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:168)
	at co.rsk.net.BlockSyncService.processBlock(BlockSyncService.java:117)
	at co.rsk.net.SyncProcessor$SyncInformationImpl.processBlock(SyncProcessor.java:360)
	at co.rsk.net.sync.DownloadingBodiesSyncState.newBody(DownloadingBodiesSyncState.java:98)
	at co.rsk.net.SyncProcessor.processBodyResponse(SyncProcessor.java:130)
	at co.rsk.net.NodeMessageHandler.processBodyResponseMessage(NodeMessageHandler.java:410)
	at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:116)
	at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:210)
	at java.lang.Thread.run(Thread.java:748)
2018-10-02-08:11:14.785 ERROR [VM]  VM halted
```

A startup log after restart:

```
2018-10-02-08:12:26.000 INFO [fullnoderunner]  Shutting down RSK node
2018-10-02-08:12:26.015 INFO [c.r.n.d.UDPServer]  Closing UDPListener...
2018-10-02-08:12:26.027 WARN [c.r.n.d.UDPServer]  UDP channel closed. Recreating after 5 sec pause...
2018-10-02-08:12:26.029 INFO [fullnoderunner]  RSK node Shut down
2018-10-02-08:12:28.143 INFO [config]  Config ( yes ): user properties from -Drsk.conf.file file '/etc/rsk/node.conf'
2018-10-02-08:12:28.149 INFO [config]  Config ( yes ): default properties from installer '/etc/rsk/node.conf'
2018-10-02-08:12:28.782 INFO [general]  Public IP wasn't set or resolved, using checkip.amazonaws.com to identify it...
2018-10-02-08:12:28.990 INFO [general]  Identified public IP: XXX.XXX.XXX.XXX
2018-10-02-08:12:29.205 INFO [general]  *** Loaded up to block [853758] totalDifficulty [1439935156225722305] with stateRoot [e7a6a224660794007642974bd558cc2a938b7ed83d890ce07aedc6069b526e48]
2018-10-02-08:12:29.405 INFO [general]  Local wallet enabled
2018-10-02-08:12:29.555 DEBUG [c.g.j.JsonRpcBasicServer]  created server for interface class co.rsk.rpc.Web3RskImpl with handler class co.rsk.rpc.Web3RskImpl
2018-10-02-08:12:29.558 WARN [cors]  CORS header set to '*'
2018-10-02-08:12:29.672 INFO [fullnoderunner]  Starting RSK
2018-10-02-08:12:29.673 INFO [fullnoderunner]  Running bamboo-testnet.json,  core version: 0.5.0-ORCHID
2018-10-02-08:12:29.673 INFO [general]  git.hash: [db78228]
2018-10-02-08:12:29.673 INFO [general]  build.branch: HEAD
2018-10-02-08:12:29.683 INFO [fullnoderunner]  Capability eth version: [V62]
2018-10-02-08:12:29.686 INFO [fullnoderunner]  RPC HTTP enabled
2018-10-02-08:12:29.742 INFO [fullnoderunner]  RPC WebSocket disabled
2018-10-02-08:12:29.743 INFO [c.r.n.d.UDPServer]  Discovery UDPListener started
```

Thanks in advance for feedback.

**Comment by aeidelman** [comment]
Hello @dabrosimov, thanks for your report. We're aware of the issue and it has already been solved. Having said that, the Testnet has been also restarted, so the issue should not be present anymore.

**Comment by 3mg** [comment]
The problem exists on 0.5.2

Our nodes stopped to add new blocks after 22363.

There are errors in log:

```
2018-10-24-08:22:39.095 DEBUG [discover]  14 Nodes retrieved from the PE.
2018-10-24-08:22:39.310 DEBUG [c.r.n.d.PeerExplorer]  New Peer found ip:[121.78.223.165] port[50505]
2018-10-24-08:22:39.391 DEBUG [c.r.n.d.PeerExplorer]  New Peer found ip:[18.191.81.214] port[50505]
2018-10-24-08:22:39.746 INFO [blockchain]  block: num: [22362] hash: [6b8e59], processed after: [1916099736]nano, result IMPORTED_BEST
2018-10-24-08:22:39.747 TRACE [blocksyncservice]  Trying to add block 22363 c2c185
2018-10-24-08:22:39.769 DEBUG [c.r.b.c.Context]  Creating bitcoinj 0.14.4 context.
2018-10-24-08:22:40.029 INFO [blockchain]  block: num: [22363] hash: [c2c185], processed after: [281897593]nano, result IMPORTED_BEST
2018-10-24-08:22:40.029 TRACE [blocksyncservice]  Trying to add block 22364 9dd110
2018-10-24-08:22:40.108 ERROR [newtrie]  Error non existent trie with hash 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
2018-10-24-08:22:40.108 ERROR [panic]  newtrie: Error creating trie from message 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
2018-10-24-08:22:40.110 ERROR [panic]  Stack Trace:
java.lang.Throwable: null
        at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)
        at co.rsk.trie.TrieImpl.getSnapshotTo(TrieImpl.java:1102)
        at co.rsk.db.ContractDetailsImpl.getSnapshotTo(ContractDetailsImpl.java:364)
        at co.rsk.db.RepositoryImpl.getContractDetails(RepositoryImpl.java:165)
        at co.rsk.db.RepositoryImpl.loadAccount(RepositoryImpl.java:404)
        at org.ethereum.db.RepositoryTrack.getAccountState(RepositoryTrack.java:94)
        at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:271)
        at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:291)
        at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:244)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:215)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:167)
        at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:267)
        at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:180)
        at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:191)
        at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:168)
        at co.rsk.net.BlockSyncService.processBlock(BlockSyncService.java:117)
        at co.rsk.net.SyncProcessor$SyncInformationImpl.processBlock(SyncProcessor.java:360)
        at co.rsk.net.sync.DownloadingBodiesSyncState.newBody(DownloadingBodiesSyncState.java:98)
        at co.rsk.net.SyncProcessor.processBodyResponse(SyncProcessor.java:130)
        at co.rsk.net.NodeMessageHandler.processBodyResponseMessage(NodeMessageHandler.java:410)
        at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:116)
        at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:210)
        at java.lang.Thread.run(Thread.java:748)
2018-10-24-08:22:40.110 ERROR [blockchain]  Unexpected error: 
co.rsk.trie.TrieSerializationException: Error creating trie from message 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
        at co.rsk.trie.TrieImpl.getSnapshotTo(TrieImpl.java:1104)
        at co.rsk.db.ContractDetailsImpl.getSnapshotTo(ContractDetailsImpl.java:364)
        at co.rsk.db.RepositoryImpl.getContractDetails(RepositoryImpl.java:165)
        at co.rsk.db.RepositoryImpl.loadAccount(RepositoryImpl.java:404)
        at org.ethereum.db.RepositoryTrack.getAccountState(RepositoryTrack.java:94)
        at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:271)
        at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:291)
        at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:244)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:215)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:167)
        at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:267)
        at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:180)
        at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:191)
        at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:168)
        at co.rsk.net.BlockSyncService.processBlock(BlockSyncService.java:117)
        at co.rsk.net.SyncProcessor$SyncInformationImpl.processBlock(SyncProcessor.java:360)
        at co.rsk.net.sync.DownloadingBodiesSyncState.newBody(DownloadingBodiesSyncState.java:98)
        at co.rsk.net.SyncProcessor.processBodyResponse(SyncProcessor.java:130)
        at co.rsk.net.NodeMessageHandler.processBodyResponseMessage(NodeMessageHandler.java:410)
        at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:116)
        at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:210)
        at java.lang.Thread.run(Thread.java:748)
2018-10-24-08:22:40.112 DEBUG [c.r.n.d.PeerExplorer]  New Peer found ip:[54.191.165.247] port[50505]
2018-10-24-08:22:40.128 TRACE [blocksyncservice]  Trying to add block 22364 9dd110
2018-10-24-08:22:40.130 ERROR [newtrie]  Error non existent trie with hash 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
2018-10-24-08:22:40.130 ERROR [panic]  newtrie: Error creating trie from message 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
2018-10-24-08:22:40.131 ERROR [panic]  Stack Trace:
java.lang.Throwable: null
        at co.rsk.panic.PanicProcessor.panic(PanicProcessor.java:33)
        at co.rsk.trie.TrieImpl.getSnapshotTo(TrieImpl.java:1102)
        at co.rsk.db.ContractDetailsImpl.getSnapshotTo(ContractDetailsImpl.java:364)
        at co.rsk.db.RepositoryImpl.getContractDetails(RepositoryImpl.java:165)
        at co.rsk.db.RepositoryImpl.loadAccount(RepositoryImpl.java:404)
        at org.ethereum.db.RepositoryTrack.getAccountState(RepositoryTrack.java:94)
        at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:271)
        at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:291)
        at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:244)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:215)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:167)
        at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:267)
        at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:180)
        at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:191)
        at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:168)
        at co.rsk.net.BlockSyncService.processBlock(BlockSyncService.java:117)
        at co.rsk.net.SyncProcessor$SyncInformationImpl.processBlock(SyncProcessor.java:360)
        at co.rsk.net.sync.DownloadingBodiesSyncState.newBody(DownloadingBodiesSyncState.java:98)
        at co.rsk.net.SyncProcessor.processBodyResponse(SyncProcessor.java:130)
        at co.rsk.net.NodeMessageHandler.processBodyResponseMessage(NodeMessageHandler.java:410)
        at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:116)
        at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:210)
        at java.lang.Thread.run(Thread.java:748)
2018-10-24-08:22:40.131 ERROR [blockchain]  Unexpected error: 
co.rsk.trie.TrieSerializationException: Error creating trie from message 59f7ecc9c73b19619278107263117f44ac38bf6b633569b88720d83317104178
        at co.rsk.trie.TrieImpl.getSnapshotTo(TrieImpl.java:1104)
        at co.rsk.db.ContractDetailsImpl.getSnapshotTo(ContractDetailsImpl.java:364)
        at co.rsk.db.RepositoryImpl.getContractDetails(RepositoryImpl.java:165)
        at co.rsk.db.RepositoryImpl.loadAccount(RepositoryImpl.java:404)
        at org.ethereum.db.RepositoryTrack.getAccountState(RepositoryTrack.java:94)
        at org.ethereum.db.RepositoryTrack.getCode(RepositoryTrack.java:271)
        at org.ethereum.core.TransactionExecutor.call(TransactionExecutor.java:291)
        at org.ethereum.core.TransactionExecutor.execute(TransactionExecutor.java:244)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:215)
        at co.rsk.core.bc.BlockExecutor.execute(BlockExecutor.java:167)
        at co.rsk.core.bc.BlockChainImpl.internalTryToConnect(BlockChainImpl.java:267)
        at co.rsk.core.bc.BlockChainImpl.tryToConnect(BlockChainImpl.java:180)
        at co.rsk.net.BlockSyncService.getConnectedBlocks(BlockSyncService.java:191)
        at co.rsk.net.BlockSyncService.connectBlocksAndDescendants(BlockSyncService.java:168)
        at co.rsk.net.BlockSyncService.processBlock(BlockSyncService.java:117)
        at co.rsk.net.SyncProcessor$SyncInformationImpl.processBlock(SyncProcessor.java:360)
        at co.rsk.net.sync.DownloadingBodiesSyncState.newBody(DownloadingBodiesSyncState.java:98)
        at co.rsk.net.SyncProcessor.processBodyResponse(SyncProcessor.java:130)
        at co.rsk.net.NodeMessageHandler.processBodyResponseMessage(NodeMessageHandler.java:410)
        at co.rsk.net.NodeMessageHandler.processMessage(NodeMessageHandler.java:116)
        at co.rsk.net.NodeMessageHandler.run(NodeMessageHandler.java:210)
        at java.lang.Thread.run(Thread.java:748)
2018-10-24-08:22:40.147 TRACE [syncprocessor]  Invalid block received from node NodeID{47ad780a0a2f10e3ee4d8fef07f0012baac96c9be99de01af5e58ba5d3650c2714cc188f7ed886cba5ee3f822fc2bb0fe3fddedfff77a1b3dc88478ff42607b4} 22364 9dd110
2018-10-24-08:22:40.148 DEBUG [messageProcess]  Message[BODY_RESPONSE_MESSAGE] processed after [5391645062] nano.
2018-10-24-08:22:40.148 DEBUG [messageProcess]  Queued Messages: 3
2018-10-24-08:22:40.148 TRACE [syncprocessor]  Process body response from node NodeID{17182cff7a494ba689d096cb9d8bb0b4164491d45086458c1defabc535038e3d9c48cad0957aa877ae010e2a07b970205924b41149a825a35f07c87959b17437}
```

**Comment by riccardopersiani** [comment]
We are experiencing this issue as well. 
Version 0.5.2.
Stuck at the block 22636.
